import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/styles.scss'
import Header from '@/components/server/layout/header'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body id='__next' className={inter.className}>
        <Header/>
        {children}
        </body>
    </html>
  )
}
